plugins {
	id 'fabric-loom' version '1.10.5'
	id 'maven-publish'
}

java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

def ENV = System.getenv()
base.archivesName = project.archives_base_name
version = ENV.BUILD_VERSION ?: project.mod_version
group = project.maven_group

repositories {
	maven { url = "https://maven.blamejared.com" }
	maven { url = "https://jitpack.io" }
}

dependencies {
	//to change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	def patchouli = "vazkii.patchouli:Patchouli:${patchouli_version}"
	modImplementation patchouli
	include patchouli

}

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

// strip comments from JSON files
tasks.withType(ProcessResources).configureEach {
	filesMatching("**/*.json") {
		it.filter {
			it.strip().startsWith("//") ? null : it
		}
	}
}

// generate sources jar
tasks.register('sourcesJar', Jar) {
	dependsOn classes
	from sourceSets.main.allSource
}

jar {
	from "LICENSE"
}

loom {
    accessWidenerPath = file("src/main/resources/automotons.accesswidener")
}