name: Upload Release Artifacts

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - name: Setup ENV
        run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble Artifacts with Gradle
        env:
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
          BUILD_VERSION: ${{ env.TAG }}
        run: ./gradlew assemble
      - name: Upload Release Artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          release-tag: ${{ env.TAG }}
          repo-token: ${{ github.token }}
          files: 'build/libs/*[!-dev].jar'
